services:
  - type: web
    name: billing-software
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.17.0
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false